const WINDOWS_FONT_FAMILY_LIST = [
    "Abadi MT",
    "Agency FB",
    "Aharoni Bold",
    "Aldhabi",
    "Algerian",
    "Almanac MT",
    "American Uncial",
    "Andale Mono",
    "Andalus",
    "Andy",
    "AngsanaUPC",
    "Angsana New",
    "Aparajita",
    "Aptos",
    "Arabic Transparent",
    "Arabic Typesetting",
    "Arial",
    "Arial Black",
    "Arial Narrow",
    "Arial Narrow Special",
    "Arial Nova",
    "Arial Rounded MT",
    "Arial Special",
    "Arial Unicode MS",
    "Augsburger Initials",
    "Avenir Next LT Pro",
    "Bahnschrift",
    "Baskerville Old Face",
    "Batang & BatangChe",
    "Bauhaus 93",
    "Beesknees ITC",
    "Bell MT",
    "Bembo",
    "Berlin Sans FB",
    "Bernard MT Condensed",
    "Bickley Script",
    "Biome",
    "BIZ UDGothic",
    "BIZ UDMincho",
    "BIZ UDMincho Medium",
    "Blackadder ITC",
    "Bodoni MT",
    "Bodoni MT Condensed",
    "Bon Apetit MT",
    "Bookman Old Style",
    "Bookshelf Symbol",
    "Book Antiqua",
    "Bradley Hand ITC",
    "Braggadocio",
    "BriemScript",
    "Britannic Bold",
    "Broadway",
    "BrowalliaUPC",
    "Browallia New",
    "Brush Script MT",
    "Calibri",
    "Californian FB",
    "Calisto MT",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Cariadings",
    "Castellar",
    "Cavolini",
    "Centaur",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Chiller",
    "Colonna MT",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Contemporary Brush",
    "Cooper Black",
    "Copperplate Gothic",
    "Corbel",
    "CordiaUPC",
    "Cordia New",
    "Courier New",
    "Curlz MT",
    "Dante",
    "DaunPenh",
    "David",
    "Daytona",
    "Desdemona",
    "DFKai-SB",
    "DilleniaUPC",
    "Directions MT",
    "DokChampa",
    "Dotum & DotumChe",
    "Ebrima",
    "Eckmann",
    "Edda",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Enviro",
    "Eras ITC",
    "Estrangelo Edessa",
    "EucrosiaUPC",
    "Euphemia",
    "Eurostile",
    "FangSong",
    "Felix Titling",
    "Fine Hand",
    "Fixed Miriam Transparent",
    "Flexure",
    "Footlight MT",
    "Forte",
    "Franklin Gothic",
    "Franklin Gothic Medium",
    "FrankRuehl",
    "FreesiaUPC",
    "Freestyle Script",
    "French Script MT",
    "Futura",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Garamond MT",
    "Gautami",
    "Georgia",
    "Georgia Ref",
    "Gigi",
    "Gill Sans MT",
    "Gill Sans MT Condensed",
    "Gisha",
    "Gloucester",
    "Goudy Old Style",
    "Goudy Stout",
    "Gradl",
    "Grotesque",
    "Gulim & GulimChe",
    "Gungsuh & GungsuhChe",
    "Hadassah Friedlaender",
    "Haettenschweiler",
    "Harlow Solid Italic",
    "Harrington",
    "HGSoeiKakugothicUB",
    "High Tower Text",
    "Holidays MT",
    "HoloLens MDL2 Assets",
    "Impact",
    "Imprint MT Shadow",
    "Informal Roman",
    "IrisUPC",
    "Iskoola Pota",
    "JasmineUPC",
    "Javanese Text",
    "Jokerman",
    "Juice ITC",
    "KaiTi",
    "Kalinga",
    "Kartika",
    "Keystrokes MT",
    "Khmer UI",
    "Kigelia",
    "Kino MT",
    "KodchiangUPC",
    "Kokila",
    "Kristen ITC",
    "Kunstler Script",
    "Lao UI",
    "Latha",
    "LCD",
    "Leelawadee",
    "Levenim MT",
    "LilyUPC",
    "Lucida Blackletter",
    "Lucida Bright",
    "Lucida Bright Math",
    "Lucida Calligraphy",
    "Lucida Console",
    "Lucida Fax",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Lucida Sans Unicode",
    "Magneto",
    "Maiandra GD",
    "Malgun Gothic",
    "Mangal",
    "Map Symbols",
    "Marlett",
    "Matisse ITC",
    "Matura MT Script Capitals",
    "McZee",
    "Mead Bold",
    "Meiryo",
    "Mercurius Script MT Bold",
    "Microsoft GothicNeo",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei UI",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft Uighur",
    "Microsoft YaHei",
    "Microsoft YaHei UI",
    "Microsoft Yi Baiti",
    "MingLiU",
    "MingLiU-ExtB",
    "MingLiU_HKSCS",
    "MingLiU_HKSCS-ExtB",
    "Minion Web",
    "Miriam",
    "Miriam Fixed",
    "Mistral",
    "Modern Love",
    "Modern No. 20",
    "Mongolian Baiti",
    "Monotype.com",
    "Monotype Corsiva",
    "Monotype Sorts",
    "MoolBoran",
    "MS Gothic",
    "MS LineDraw",
    "MS Mincho",
    "MS Outlook",
    "MS PGothic",
    "MS PMincho",
    "MS Reference",
    "MS UI Gothic",
    "MT Extra",
    "MV Boli",
    "Myanmar Text",
    "Narkisim",
    "News Gothic MT",
    "New Caledonia",
    "Niagara",
    "Nirmala UI",
    "Nyala",
    "OCR-B-Digits",
    "OCRB",
    "OCR A Extended",
    "Old English Text MT",
    "Onyx",
    "Palace Script MT",
    "Palatino Linotype",
    "Papyrus",
    "Parade",
    "Parchment",
    "Parties MT",
    "Peignot Medium",
    "Pepita MT",
    "Perpetua",
    "Perpetua Titling MT",
    "Placard Condensed",
    "Plantagenet Cherokee",
    "Playbill",
    "PMingLiU",
    "PMingLiU-ExtB",
    "Poor Richard",
    "Posterama",
    "Pristina",
    "Quire Sans",
    "Raavi",
    "Rage Italic",
    "Ransom",
    "Ravie",
    "RefSpecialty",
    "Rockwell",
    "Rockwell Nova",
    "Rod",
    "Runic MT Condensed",
    "Sabon Next LT",
    "Sagona",
    "Sakkal Majalla",
    "Script MT Bold",
    "Segoe Chess",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Symbol",
    "Selawik",
    "Shonar Bangla",
    "Showcard Gothic",
    "Shruti",
    "Signs MT",
    "SimHei",
    "Simplified Arabic Fixed",
    "SimSun",
    "SimSun-ExtB",
    "Sitka",
    "NSimSun",
    "Snap ITC",
    "Sports MT",
    "STCaiyun",
    "Stencil",
    "STFangsong",
    "STHupo",
    "STKaiti",
    "Stop",
    "STXihei",
    "STXingkai",
    "STXinwei",
    "STZhongsong",
    "Sylfaen",
    "Symbol",
    "Tahoma",
    "Tempo Grunge",
    "Tempus Sans ITC",
    "Temp Installer Font",
    "The Hand",
    "The Serif Hand",
    "Times New Roman",
    "Times New Roman Special",
    "Tisa Offc Serif Pro",
    "Traditional Arabic",
    "Transport MT",
    "Trebuchet MS",
    "Tunga",
    "Tw Cen MT",
    "Univers",
    "Urdu Typesetting",
    "Utsaah",
    "Vacation MT",
    "Vani",
    "Verdana",
    "Verdana Ref",
    "Vijaya",
    "Viner Hand ITC",
    "Vivaldi",
    "Vixar ASCI",
    "Vladimir Script",
    "Vrinda",
    "Walbaum",
    "Webdings",
    "Westminster",
    "Wide Latin",
    "Wingdings"
];

const MS_OFFICE_FONT_FAMILY_LIST = [
    "HGGothicE",
    "HGMinchoE",
    "HGPGothicE",
    "HGPMinchoE",
    "HGSGothicE",
    "HGSMinchoE",
    "HGPSoeiKakugothicUB",
    "HGPSoeiKakupoptai",
];

const APPLE_FONT_FAMILY_LIST = [
    "Academy Engraved LET Plain:1.0",
    "Adelle Sans Devanagari Bold",
    "Adelle Sans Devanagari Extrabold",
    "Adelle Sans Devanagari Heavy",
    "Adelle Sans Devanagari Light",
    "Adelle Sans Devanagari Regular",
    "Adelle Sans Devanagari Semibold",
    "Adelle Sans Devanagari Thin",
    "AkayaKanadaka",
    "AkayaTelivigala",
    "Al Bayan Bold",
    "Al Bayan Plain",
    "Al Firat Regular",
    "Al Khalil Bold",
    "Al Khalil Regular",
    "Al Nile",
    "Al Nile Bold",
    "Al Rafidain Al Fanni",
    "Al Rafidain Regular",
    "Al Tarikh Regular",
    "Algiers Regular",
    "American Typewriter",
    "American Typewriter Bold",
    "American Typewriter Condensed",
    "American Typewriter Condensed Bold",
    "American Typewriter Condensed Light",
    "American Typewriter Light",
    "American Typewriter Semibold",
    "Andale Mono",
    "Annai MN Regular",
    "Apple Braille",
    "Apple Braille Outline 6 Dot",
    "Apple Braille Outline 8 Dot",
    "Apple Braille Pinpoint 6 Dot",
    "Apple Braille Pinpoint 8 Dot",
    "Apple Chancery",
    "Apple Color Emoji",
    "Apple LiGothic Medium",
    "Apple LiSung Light",
    "Apple SD Gothic Neo Bold",
    "Apple SD Gothic Neo ExtraBold",
    "Apple SD Gothic Neo Heavy",
    "Apple SD Gothic Neo Light",
    "Apple SD Gothic Neo Medium",
    "Apple SD Gothic Neo Regular",
    "Apple SD Gothic Neo SemiBold",
    "Apple SD Gothic Neo Thin",
    "Apple SD Gothic Neo UltraLight",
    "Apple Symbols",
    "AppleGothic Regular",
    "AppleMyungjo Regular",
    "Arial",
    "Arial Black",
    "Arial Bold",
    "Arial Bold Italic",
    "Arial Hebrew",
    "Arial Hebrew Bold",
    "Arial Hebrew Light",
    "Arial Hebrew Scholar",
    "Arial Hebrew Scholar Bold",
    "Arial Hebrew Scholar Light",
    "Arial Italic",
    "Arial Narrow",
    "Arial Narrow Bold",
    "Arial Narrow Bold Italic",
    "Arial Narrow Italic",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "Arima Koshi",
    "Arima Koshi Black",
    "Arima Koshi Bold",
    "Arima Koshi ExtraBold",
    "Arima Koshi ExtraLight",
    "Arima Koshi Light",
    "Arima Koshi Medium",
    "Arima Koshi Thin",
    "Arima Madurai",
    "Arima Madurai Black",
    "Arima Madurai Bold",
    "Arima Madurai ExtraLight",
    "Arima Madurai Light",
    "Arima Madurai Medium",
    "Arima Madurai Semi Bold",
    "Arima Madurai Thin",
    "Asphalt Medium",
    "Athelas Bold",
    "Athelas Bold Italic",
    "Athelas Italic",
    "Athelas Regular",
    "Avenir Black",
    "Avenir Black Oblique",
    "Avenir Book",
    "Avenir Book Oblique",
    "Avenir Heavy",
    "Avenir Heavy Oblique",
    "Avenir Light",
    "Avenir Light Oblique",
    "Avenir Medium",
    "Avenir Medium Oblique",
    "Avenir Next Bold",
    "Avenir Next Bold Italic",
    "Avenir Next Condensed Bold",
    "Avenir Next Condensed Bold Italic",
    "Avenir Next Condensed Demi Bold",
    "Avenir Next Condensed Demi Bold Italic",
    "Avenir Next Condensed Heavy",
    "Avenir Next Condensed Heavy Italic",
    "Avenir Next Condensed Italic",
    "Avenir Next Condensed Medium",
    "Avenir Next Condensed Medium Italic",
    "Avenir Next Condensed Regular",
    "Avenir Next Condensed Ultra Light",
    "Avenir Next Condensed Ultra Light Italic",
    "Avenir Next Demi Bold",
    "Avenir Next Demi Bold Italic",
    "Avenir Next Heavy",
    "Avenir Next Heavy Italic",
    "Avenir Next Italic",
    "Avenir Next Medium",
    "Avenir Next Medium Italic",
    "Avenir Next Regular",
    "Avenir Next Ultra Light",
    "Avenir Next Ultra Light Italic",
    "Avenir Oblique",
    "Avenir Roman",
    "Ayuthaya",
    "BIZ UDGothic",
    "BIZ UDGothic Bold",
    "BIZ UDMincho",
    "BM DoHyeon OTF",
    "BM HANNA 11yrs old OTF",
    "BM HANNA Air OTF",
    "BM HANNA Pro OTF",
    "BM JUA OTF",
    "BM KIRANGHAERANG OTF",
    "BM YEONSUNG OTF",
    "Baghdad Regular",
    "Bai Jamjuree Bold",
    "Bai Jamjuree Bold Italic",
    "Bai Jamjuree ExtraLight",
    "Bai Jamjuree ExtraLight Italic",
    "Bai Jamjuree Italic",
    "Bai Jamjuree Light",
    "Bai Jamjuree Light Italic",
    "Bai Jamjuree Medium",
    "Bai Jamjuree Medium Italic",
    "Bai Jamjuree Regular",
    "Bai Jamjuree SemiBold",
    "Bai Jamjuree SemiBold Italic",
    "Balega Regular",
    "Baloo 2 Bold",
    "Baloo 2 ExtraBold",
    "Baloo 2 Medium",
    "Baloo 2 Regular",
    "Baloo 2 SemiBold",
    "Baloo Bhai 2 Bold",
    "Baloo Bhai 2 ExtraBold",
    "Baloo Bhai 2 Medium",
    "Baloo Bhai 2 Regular",
    "Baloo Bhai 2 SemiBold",
    "Baloo Bhaijaan Regular",
    "Baloo Bhaina 2 Bold",
    "Baloo Bhaina 2 ExtraBold",
    "Baloo Bhaina 2 Medium",
    "Baloo Bhaina 2 Regular",
    "Baloo Bhaina 2 SemiBold",
    "Baloo Chettan 2 Bold",
    "Baloo Chettan 2 ExtraBold",
    "Baloo Chettan 2 Medium",
    "Baloo Chettan 2 Regular",
    "Baloo Chettan 2 SemiBold",
    "Baloo Da 2 Bold",
    "Baloo Da 2 ExtraBold",
    "Baloo Da 2 Medium",
    "Baloo Da 2 Regular",
    "Baloo Da 2 SemiBold",
    "Baloo Paaji 2 Bold",
    "Baloo Paaji 2 ExtraBold",
    "Baloo Paaji 2 Medium",
    "Baloo Paaji 2 Regular",
    "Baloo Paaji 2 SemiBold",
    "Baloo Tamma 2 Bold",
    "Baloo Tamma 2 ExtraBold",
    "Baloo Tamma 2 Medium",
    "Baloo Tamma 2 Regular",
    "Baloo Tamma 2 SemiBold",
    "Baloo Tammudu 2 Bold",
    "Baloo Tammudu 2 ExtraBold",
    "Baloo Tammudu 2 Medium",
    "Baloo Tammudu 2 Regular",
    "Baloo Tammudu 2 SemiBold",
    "Baloo Thambi 2 Bold",
    "Baloo Thambi 2 ExtraBold",
    "Baloo Thambi 2 Medium",
    "Baloo Thambi 2 Regular",
    "Baloo Thambi 2 SemiBold",
    "Bangla MN",
    "Bangla MN Bold",
    "Bangla Sangam MN",
    "Bangla Sangam MN Bold",
    "Bank Gothic Light",
    "Bank Gothic Medium",
    "Baoli SC Regular",
    "Baoli TC Regular",
    "Baskerville",
    "Baskerville Bold",
    "Baskerville Bold Italic",
    "Baskerville Italic",
    "Baskerville SemiBold",
    "Baskerville SemiBold Italic",
    "Basra Bold",
    "Basra Regular",
    "Bebas Neue",
    "Beirut Regular",
    "BiauKai",
    "BiauKaiHK Regular",
    "BiauKaiTC Regular",
    "Big Caslon Medium",
    "Blackmoor LET Plain:2.0",
    "BlairMdITC TT Medium",
    "Bodoni 72 Bold",
    "Bodoni 72 Book",
    "Bodoni 72 Book Italic",
    "Bodoni 72 Oldstyle Bold",
    "Bodoni 72 Oldstyle Book",
    "Bodoni 72 Oldstyle Book Italic",
    "Bodoni 72 Smallcaps Book",
    "Bodoni Ornaments",
    "Bodoni SvtyTwo ITC TT Bold",
    "Bodoni SvtyTwo ITC TT Book",
    "Bodoni SvtyTwo ITC TT BookIta",
    "Book Antiqua",
    "Book Antiqua Bold",
    "Book Antiqua Bold Italic",
    "Book Antiqua Italic",
    "Bookman Old Style",
    "Bookman Old Style Bold",
    "Bookman Old Style Bold Italic",
    "Bookman Old Style Italic",
    "Bordeaux Roman Bold LET Plain",
    "Bradley Hand Bold",
    "Braganza",
    "Brill Italic Bold Italic",
    "Brill Italic Italic",
    "Brill Italic Medium Italic",
    "Brill Italic Semibold Italic",
    "Brill Roman Bold",
    "Brill Roman Medium",
    "Brill Roman Regular",
    "Brill Roman Semibold",
    "Brush Script MT Italic",
    "Cambay Devanagari Bold",
    "Cambay Devanagari Bold Oblique",
    "Cambay Devanagari Oblique",
    "Cambay Devanagari Regular",
    "Canela Bold",
    "Canela Bold Italic",
    "Canela Deck Bold",
    "Canela Deck Bold Italic",
    "Canela Deck Medium",
    "Canela Deck Medium Italic",
    "Canela Deck Regular",
    "Canela Deck Regular Italic",
    "Canela Regular",
    "Canela Regular Italic",
    "Canela Text Bold",
    "Canela Text Bold Italic",
    "Canela Text Medium",
    "Canela Text Medium Italic",
    "Canela Text Regular",
    "Canela Text Regular Italic",
    "Capitals",
    "Carlito",
    "Carlito Bold",
    "Carlito Bold Italic",
    "Carlito Italic",
    "Catamaran Black",
    "Catamaran Bold",
    "Catamaran ExtraBold",
    "Catamaran ExtraLight",
    "Catamaran Light",
    "Catamaran Medium",
    "Catamaran Regular",
    "Catamaran SemiBold",
    "Catamaran Thin",
    "Century Gothic",
    "Century Gothic Bold",
    "Century Gothic Bold Italic",
    "Century Gothic Italic",
    "Century Schoolbook",
    "Century Schoolbook Bold",
    "Century Schoolbook Bold Italic",
    "Century Schoolbook Italic",
    "Chakra Petch Bold",
    "Chakra Petch Bold Italic",
    "Chakra Petch ExtraLight",
    "Chakra Petch ExtraLight Italic",
    "Chakra Petch Italic",
    "Chakra Petch Light",
    "Chakra Petch Light Italic",
    "Chakra Petch Medium",
    "Chakra Petch Medium Italic",
    "Chakra Petch Regular",
    "Chakra Petch SemiBold",
    "Chakra Petch SemiBold Italic",
    "Chalkboard",
    "Chalkboard Bold",
    "Chalkboard SE Bold",
    "Chalkboard SE Light",
    "Chalkboard SE Regular",
    "Chalkduster",
    "Charcoal CY",
    "Charm Bold",
    "Charm Regular",
    "Charmonman Bold",
    "Charmonman Regular",
    "Charter Black",
    "Charter Black Italic",
    "Charter Bold",
    "Charter Bold Italic",
    "Charter Italic",
    "Charter Roman",
    "Cochin",
    "Cochin Bold",
    "Cochin Bold Italic",
    "Cochin Italic",
    "Comic Sans MS",
    "Comic Sans MS Bold",
    "Copperplate",
    "Copperplate Bold",
    "Copperplate Light",
    "Corsiva Hebrew",
    "Corsiva Hebrew Bold",
    "Courier",
    "Courier Bold",
    "Courier Bold Oblique",
    "Courier New",
    "Courier New Bold",
    "Courier New Bold Italic",
    "Courier New Italic",
    "Courier Oblique",
    "DB LCD Temp Black",
    "DFKaiShu-SB-Estd-BF",
    "DIN Alternate Bold",
    "DIN Condensed Bold",
    "Damascus Bold",
    "Damascus Light",
    "Damascus Medium",
    "Damascus Regular",
    "Damascus Semi Bold",
    "Dash Practice",
    "Dash Regular",
    "Dear Joe Four",
    "Dear Joe Four Small",
    "Dear Joe Four Small Semibold",
    "DecoType Naskh Regular",
    "Devanagari MT",
    "Devanagari MT Bold",
    "Devanagari Sangam MN",
    "Devanagari Sangam MN Bold",
    "Didot",
    "Didot Bold",
    "Didot Italic",
    "Dijla Regular",
    "Diwan Kufi Regular",
    "Diwan Thuluth Regular",
    "Domaine Display",
    "Domaine Display Bold",
    "Domaine Display Bold Italic",
    "Domaine Display Italic",
    "Domaine Display Medium",
    "Domaine Display Medium Italic",
    "Druk Bold",
    "Druk Bold Italic",
    "Druk Heavy",
    "Druk Heavy Italic",
    "Druk Medium",
    "Druk Medium Italic",
    "Druk Super",
    "Druk Super Italic",
    "Druk Text Bold",
    "Druk Wide Bold",
    "Druk Wide Bold Italic",
    "Druk Wide Medium",
    "Druk Wide Medium Italic",
    "Euphemia UCAS",
    "Euphemia UCAS Bold",
    "Euphemia UCAS Italic",
    "Fahkwang Bold",
    "Fahkwang Bold Italic",
    "Fahkwang ExtraLight",
    "Fahkwang ExtraLight Italic",
    "Fahkwang Italic",
    "Fahkwang Light",
    "Fahkwang Light Italic",
    "Fahkwang Medium",
    "Fahkwang Medium Italic",
    "Fahkwang Regular",
    "Fahkwang SemiBold",
    "Fahkwang SemiBold Italic",
    "Fakt Slab Stencil Pro Medium",
    "Farah Regular",
    "Farisi Regular",
    "Forgotten Futurist Bold",
    "Forgotten Futurist Bold Italic",
    "Forgotten Futurist Italic",
    "Forgotten Futurist Regular",
    "Forgotten Futurist Shadow",
    "Founders Grotesk",
    "Founders Grotesk Bold",
    "Founders Grotesk Bold Italic",
    "Founders Grotesk Condensed",
    "Founders Grotesk Condensed Bold",
    "Founders Grotesk Condensed Semibold",
    "Founders Grotesk Light",
    "Founders Grotesk Light Italic",
    "Founders Grotesk Medium",
    "Founders Grotesk Medium Italic",
    "Founders Grotesk Regular Italic",
    "Founders Grotesk Semibold",
    "Founders Grotesk Semibold Italic",
    "Founders Grotesk Text",
    "Founders Grotesk Text Bold",
    "Founders Grotesk Text Bold Italic",
    "Founders Grotesk Text Regular Italic",
    "Futura Bold",
    "Futura Condensed ExtraBold",
    "Futura Condensed Medium",
    "Futura Medium",
    "Futura Medium Italic",
    "GB18030 Bitmap",
    "Galvji",
    "Galvji Bold",
    "Galvji Bold Oblique",
    "Galvji Oblique",
    "Garamond",
    "Garamond Bold",
    "Garamond Bold Italic",
    "Garamond Italic",
    "Geeza Pro Bold",
    "Geeza Pro Regular",
    "Geneva",
    "Geneva CY",
    "Georgia",
    "Georgia Bold",
    "Georgia Bold Italic",
    "Georgia Italic",
    "Gill Sans",
    "Gill Sans Bold",
    "Gill Sans Bold Italic",
    "Gill Sans Italic",
    "Gill Sans Light",
    "Gill Sans Light Italic",
    "Gill Sans SemiBold",
    "Gill Sans SemiBold Italic",
    "Gill Sans UltraBold",
    "Gotu",
    "Grantha Sangam MN Black",
    "Grantha Sangam MN Bold",
    "Grantha Sangam MN DemiBold",
    "Grantha Sangam MN Light",
    "Grantha Sangam MN Medium",
    "Grantha Sangam MN Regular",
    "Graphik",
    "Graphik Bold",
    "Graphik Bold Italic",
    "Graphik Compact Bold",
    "Graphik Compact Bold Italic",
    "Graphik Compact Medium",
    "Graphik Compact Medium Italic",
    "Graphik Compact Regular",
    "Graphik Compact Regular Italic",
    "Graphik Compact Semibold",
    "Graphik Compact Semibold Italic",
    "Graphik Light",
    "Graphik Light Italic",
    "Graphik Medium",
    "Graphik Medium Italic",
    "Graphik Regular Italic",
    "Graphik Semibold",
    "Graphik Semibold Italic",
    "Gujarati MT",
    "Gujarati MT Bold",
    "Gujarati Sangam MN",
    "Gujarati Sangam MN Bold",
    "GungSeo Regular",
    "Gurmukhi MN",
    "Gurmukhi MN Bold",
    "Gurmukhi MT",
    "Gurmukhi Sangam MN",
    "Gurmukhi Sangam MN Bold",
    "Hannotate SC Bold",
    "Hannotate SC Regular",
    "Hannotate TC Bold",
    "Hannotate TC Regular",
    "HanziPen SC Bold",
    "HanziPen SC Regular",
    "HanziPen TC Bold",
    "HanziPen TC Regular",
    "HeadLineA Regular",
    "Hei Regular",
    "Heiti SC Light",
    "Heiti SC Medium",
    "Heiti TC Light",
    "Heiti TC Medium",
    "Helvetica",
    "Helvetica Bold",
    "Helvetica Bold Oblique",
    "Helvetica CY Bold",
    "Helvetica CY BoldOblique",
    "Helvetica CY Oblique",
    "Helvetica CY Plain",
    "Helvetica Light",
    "Helvetica Light Oblique",
    "Helvetica Neue",
    "Helvetica Neue Bold",
    "Helvetica Neue Bold Italic",
    "Helvetica Neue Condensed Black",
    "Helvetica Neue Condensed Bold",
    "Helvetica Neue Italic",
    "Helvetica Neue Light",
    "Helvetica Neue Light Italic",
    "Helvetica Neue Medium",
    "Helvetica Neue Medium Italic",
    "Helvetica Neue Thin",
    "Helvetica Neue Thin Italic",
    "Helvetica Neue UltraLight",
    "Helvetica Neue UltraLight Italic",
    "Helvetica Oblique",
    "Herculanum",
    "Hiragino Kaku Gothic Pro W3",
    "Hiragino Kaku Gothic Pro W6",
    "Hiragino Kaku Gothic ProN W3",
    "Hiragino Kaku Gothic ProN W6",
    "Hiragino Kaku Gothic Std W8",
    "Hiragino Kaku Gothic StdN W8",
    "Hiragino Maru Gothic Pro W4",
    "Hiragino Maru Gothic ProN W4",
    "Hiragino Mincho Pro W3",
    "Hiragino Mincho Pro W6",
    "Hiragino Mincho ProN W3",
    "Hiragino Mincho ProN W6",
    "Hiragino Sans CNS W3",
    "Hiragino Sans CNS W6",
    "Hiragino Sans GB W3",
    "Hiragino Sans GB W6",
    "Hiragino Sans TC W3",
    "Hiragino Sans TC W6",
    "Hiragino Sans W0",
    "Hiragino Sans W1",
    "Hiragino Sans W2",
    "Hiragino Sans W3",
    "Hiragino Sans W4",
    "Hiragino Sans W5",
    "Hiragino Sans W6",
    "Hiragino Sans W7",
    "Hiragino Sans W8",
    "Hiragino Sans W9",
    "Hoefler Text",
    "Hoefler Text Black",
    "Hoefler Text Black Italic",
    "Hoefler Text Italic",
    "Hoefler Text Ornaments",
    "Hopper Script Regular",
    "Hubballi",
    "ITF Devanagari Bold",
    "ITF Devanagari Book",
    "ITF Devanagari Demi",
    "ITF Devanagari Light",
    "ITF Devanagari Marathi Bold",
    "ITF Devanagari Marathi Book",
    "ITF Devanagari Marathi Demi",
    "ITF Devanagari Marathi Light",
    "ITF Devanagari Marathi Medium",
    "ITF Devanagari Medium",
    "Impact",
    "InaiMathi",
    "InaiMathi Bold",
    "Iowan Old Style Black",
    "Iowan Old Style Black Italic",
    "Iowan Old Style Bold",
    "Iowan Old Style Bold Italic",
    "Iowan Old Style Italic",
    "Iowan Old Style Roman",
    "Iowan Old Style Titling",
    "Jaini",
    "Jaini Purva",
    "Jazz LET Plain:1.0",
    "Journal Sans New Inline",
    "K2D Bold",
    "K2D Bold Italic",
    "K2D ExtraBold",
    "K2D ExtraBold Italic",
    "K2D ExtraLight",
    "K2D ExtraLight Italic",
    "K2D Italic",
    "K2D Light",
    "K2D Light Italic",
    "K2D Medium",
    "K2D Medium Italic",
    "K2D Regular",
    "K2D SemiBold",
    "K2D SemiBold Italic",
    "K2D Thin",
    "K2D Thin Italic",
    "Kai Regular",
    "Kailasa Bold",
    "Kailasa Regular",
    "Kaiti SC Black",
    "Kaiti SC Bold",
    "Kaiti SC Regular",
    "Kaiti TC Black",
    "Kaiti TC Bold",
    "Kaiti TC Regular",
    "Kannada MN",
    "Kannada MN Bold",
    "Kannada Sangam MN",
    "Kannada Sangam MN Bold",
    "Katari Black",
    "Katari Black Italic",
    "Katari Bold",
    "Katari Bold Italic",
    "Katari Italic",
    "Katari Medium",
    "Katari Medium Italic",
    "Katari Regular",
    "Kavivanar",
    "Kefa Bold",
    "Kefa Regular",
    "Khmer MN",
    "Khmer MN Bold",
    "Khmer Sangam MN",
    "Kigelia Arabic Bold",
    "Kigelia Arabic Extrabold",
    "Kigelia Arabic Light",
    "Kigelia Arabic Regular",
    "Kigelia Arabic Semibold",
    "Kigelia Bold",
    "Kigelia Bold Italic",
    "Kigelia Extrabold",
    "Kigelia Extrabold Italic",
    "Kigelia Italic",
    "Kigelia Light",
    "Kigelia Light Italic",
    "Kigelia Regular",
    "Kigelia Semibold",
    "Kigelia Semibold Italic",
    "Klee Demibold",
    "Klee Medium",
    "KoHo Bold",
    "KoHo Bold Italic",
    "KoHo ExtraLight",
    "KoHo ExtraLight Italic",
    "KoHo Italic",
    "KoHo Light",
    "KoHo Light Italic",
    "KoHo Medium",
    "KoHo Medium Italic",
    "KoHo Regular",
    "KoHo SemiBold",
    "KoHo SemiBold Italic",
    "Kodchasan Bold",
    "Kodchasan Bold Italic",
    "Kodchasan ExtraLight",
    "Kodchasan ExtraLight Italic",
    "Kodchasan Italic",
    "Kodchasan Light",
    "Kodchasan Light Italic",
    "Kodchasan Medium",
    "Kodchasan Medium Italic",
    "Kodchasan Regular",
    "Kodchasan SemiBold",
    "Kodchasan SemiBold Italic",
    "Kohinoor Bangla",
    "Kohinoor Bangla Bold",
    "Kohinoor Bangla Light",
    "Kohinoor Bangla Medium",
    "Kohinoor Bangla Semibold",
    "Kohinoor Devanagari Bold",
    "Kohinoor Devanagari Light",
    "Kohinoor Devanagari Medium",
    "Kohinoor Devanagari Regular",
    "Kohinoor Devanagari Semibold",
    "Kohinoor Gujarati Bold",
    "Kohinoor Gujarati Light",
    "Kohinoor Gujarati Medium",
    "Kohinoor Gujarati Regular",
    "Kohinoor Gujarati Semibold",
    "Kohinoor Telugu",
    "Kohinoor Telugu Bold",
    "Kohinoor Telugu Light",
    "Kohinoor Telugu Medium",
    "Kohinoor Telugu Semibold",
    "Kokonor Regular",
    "Koufi Abjadi Regular",
    "Krub Bold",
    "Krub Bold Italic",
    "Krub ExtraLight",
    "Krub ExtraLight Italic",
    "Krub Italic",
    "Krub Light",
    "Krub Light Italic",
    "Krub Medium",
    "Krub Medium Italic",
    "Krub Regular",
    "Krub SemiBold",
    "Krub SemiBold Italic",
    "Krungthep",
    "KufiStandardGK Regular",
    "Lahore Gurmukhi Bold",
    "Lahore Gurmukhi Light",
    "Lahore Gurmukhi Medium",
    "Lahore Gurmukhi Regular",
    "Lahore Gurmukhi SemiBold",
    "Laimoon Regular",
    "Lantinghei SC Demibold",
    "Lantinghei SC Extralight",
    "Lantinghei SC Heavy",
    "Lantinghei TC Demibold",
    "Lantinghei TC Extralight",
    "Lantinghei TC Heavy",
    "Lao MN",
    "Lao MN Bold",
    "Lao Sangam MN",
    "Lava Devanagari Bold",
    "Lava Devanagari Heavy",
    "Lava Devanagari Medium",
    "Lava Devanagari Regular",
    "Lava Kannada Bold",
    "Lava Kannada Heavy",
    "Lava Kannada Medium",
    "Lava Kannada Regular",
    "Lava Telugu Bold",
    "Lava Telugu Heavy",
    "Lava Telugu Medium",
    "Lava Telugu Regular",
    "LiHei Pro",
    "LiSong Pro",
    "Libian SC Regular",
    "Libian TC Regular",
    "LingWai SC Medium",
    "LingWai TC Medium",
    "Lucida Grande",
    "Lucida Grande Bold",
    "Luminari",
    "Maku Bold",
    "Maku Regular",
    "Malayalam MN",
    "Malayalam MN Bold",
    "Malayalam Sangam MN",
    "Malayalam Sangam MN Bold",
    "Mali Bold",
    "Mali Bold Italic",
    "Mali ExtraLight",
    "Mali ExtraLight Italic",
    "Mali Italic",
    "Mali Light",
    "Mali Light Italic",
    "Mali Medium",
    "Mali Medium Italic",
    "Mali Regular",
    "Mali SemiBold",
    "Mali SemiBold Italic",
    "Marion Bold",
    "Marion Italic",
    "Marion Regular",
    "Marker Felt Thin",
    "Marker Felt Wide",
    "Menlo Bold",
    "Menlo Bold Italic",
    "Menlo Italic",
    "Menlo Regular",
    "Microsoft Sans Serif",
    "Mishafi Gold Regular",
    "Mishafi Regular",
    "Modak",
    "Mona Lisa Solid ITC TT",
    "Monaco",
    "Mshtakan",
    "Mshtakan Bold",
    "Mshtakan BoldOblique",
    "Mshtakan Oblique",
    "Mukta Bold",
    "Mukta ExtraBold",
    "Mukta ExtraLight",
    "Mukta Light",
    "Mukta Malar Bold",
    "Mukta Malar ExtraBold",
    "Mukta Malar ExtraLight",
    "Mukta Malar Light",
    "Mukta Malar Medium",
    "Mukta Malar Regular",
    "Mukta Malar SemiBold",
    "Mukta Medium",
    "Mukta Regular",
    "Mukta SemiBold",
    "Mukta Vaani Bold",
    "Mukta Vaani ExtraBold",
    "Mukta Vaani ExtraLight",
    "Mukta Vaani Light",
    "Mukta Vaani Medium",
    "Mukta Vaani Regular",
    "Mukta Vaani SemiBold",
    "MuktaMahee Bold",
    "MuktaMahee ExtraBold",
    "MuktaMahee ExtraLight",
    "MuktaMahee Light",
    "MuktaMahee Medium",
    "MuktaMahee Regular",
    "MuktaMahee SemiBold",
    "Muna Black",
    "Muna Bold",
    "Muna Regular",
    "Myanmar MN",
    "Myanmar MN Bold",
    "Myanmar Sangam MN",
    "Myanmar Sangam MN Bold",
    "Myriad Arabic",
    "Myriad Arabic Black",
    "Myriad Arabic Black Italic",
    "Myriad Arabic Bold",
    "Myriad Arabic Bold Italic",
    "Myriad Arabic Italic",
    "Myriad Arabic Light",
    "Myriad Arabic Light Italic",
    "Myriad Arabic Semibold",
    "Myriad Arabic Semibold Italic",
    "Nadeem Regular",
    "Nanum Brush Script",
    "Nanum Pen Script",
    "NanumGothic",
    "NanumGothic Bold",
    "NanumGothic ExtraBold",
    "NanumMyeongjo",
    "NanumMyeongjo Bold",
    "NanumMyeongjo ExtraBold",
    "New Peninim MT",
    "New Peninim MT Bold",
    "New Peninim MT Bold Inclined",
    "New Peninim MT Inclined",
    "Niramit Bold",
    "Niramit Bold Italic",
    "Niramit ExtraLight",
    "Niramit ExtraLight Italic",
    "Niramit Italic",
    "Niramit Light",
    "Niramit Light Italic",
    "Niramit Medium",
    "Niramit Medium Italic",
    "Niramit Regular",
    "Niramit SemiBold",
    "Niramit SemiBold Italic",
    "Nisan Regular",
    "Nom Na Tong",
    "Noteworthy Bold",
    "Noteworthy Light",
    "Noto Nastaliq Urdu",
    "Noto Nastaliq Urdu Bold",
    "Noto Sans Adlam Regular",
    "Noto Sans Armenian Black",
    "Noto Sans Armenian Bold",
    "Noto Sans Armenian ExtraBold",
    "Noto Sans Armenian ExtraLight",
    "Noto Sans Armenian Light",
    "Noto Sans Armenian Medium",
    "Noto Sans Armenian Regular",
    "Noto Sans Armenian SemiBold",
    "Noto Sans Armenian Thin",
    "Noto Sans Avestan Regular",
    "Noto Sans Bamum Regular",
    "Noto Sans Bassa Vah Regular",
    "Noto Sans Batak Regular",
    "Noto Sans Bhaiksuki Regular",
    "Noto Sans Brahmi Regular",
    "Noto Sans Buginese Regular",
    "Noto Sans Buhid Regular",
    "Noto Sans Canadian Aboriginal Regular",
    "Noto Sans Carian Regular",
    "Noto Sans Caucasian Albanian Regular",
    "Noto Sans Chakma Regular",
    "Noto Sans Cham Regular",
    "Noto Sans Coptic Regular",
    "Noto Sans Cuneiform Regular",
    "Noto Sans Cypriot Regular",
    "Noto Sans Duployan Regular",
    "Noto Sans Egyptian Hieroglyphs Regular",
    "Noto Sans Elbasan Regular",
    "Noto Sans Glagolitic Regular",
    "Noto Sans Gothic Regular",
    "Noto Sans Gunjala Gondi Regular",
    "Noto Sans Hanifi Rohingya Regular",
    "Noto Sans Hanunoo Regular",
    "Noto Sans Hatran Regular",
    "Noto Sans Imperial Aramaic Regular",
    "Noto Sans Inscriptional Pahlavi Regular",
    "Noto Sans Inscriptional Parthian Regular",
    "Noto Sans Javanese Regular",
    "Noto Sans Kaithi Regular",
    "Noto Sans Kannada Black",
    "Noto Sans Kannada Bold",
    "Noto Sans Kannada ExtraBold",
    "Noto Sans Kannada ExtraLight",
    "Noto Sans Kannada Light",
    "Noto Sans Kannada Medium",
    "Noto Sans Kannada Regular",
    "Noto Sans Kannada SemiBold",
    "Noto Sans Kannada Thin",
    "Noto Sans Kayah Li Regular",
    "Noto Sans Kharoshthi Regular",
    "Noto Sans Khojki Regular",
    "Noto Sans Khudawadi Regular",
    "Noto Sans Lepcha Regular",
    "Noto Sans Limbu Regular",
    "Noto Sans Linear A Regular",
    "Noto Sans Linear B Regular",
    "Noto Sans Lisu Regular",
    "Noto Sans Lycian Regular",
    "Noto Sans Lydian Regular",
    "Noto Sans Mahajani Regular",
    "Noto Sans Mandaic Regular",
    "Noto Sans Manichaean Regular",
    "Noto Sans Marchen Regular",
    "Noto Sans Masaram Gondi Regular",
    "Noto Sans Meetei Mayek Regular",
    "Noto Sans Mende Kikakui Regular",
    "Noto Sans Meroitic Regular",
    "Noto Sans Miao Regular",
    "Noto Sans Modi Regular",
    "Noto Sans Mongolian",
    "Noto Sans Mro Regular",
    "Noto Sans Multani Regular",
    "Noto Sans Myanmar Black",
    "Noto Sans Myanmar Bold",
    "Noto Sans Myanmar ExtraBold",
    "Noto Sans Myanmar ExtraLight",
    "Noto Sans Myanmar Light",
    "Noto Sans Myanmar Medium",
    "Noto Sans Myanmar Regular",
    "Noto Sans Myanmar SemiBold",
    "Noto Sans Myanmar Thin",
    "Noto Sans NKo Regular",
    "Noto Sans Nabataean Regular",
    "Noto Sans New Tai Lue Regular",
    "Noto Sans Newa Regular",
    "Noto Sans Ol Chiki Regular",
    "Noto Sans Old Hungarian Regular",
    "Noto Sans Old Italic Regular",
    "Noto Sans Old North Arabian Regular",
    "Noto Sans Old Permic Regular",
    "Noto Sans Old Persian Regular",
    "Noto Sans Old South Arabian Regular",
    "Noto Sans Old Turkic Regular",
    "Noto Sans Oriya",
    "Noto Sans Oriya Bold",
    "Noto Sans Osage Regular",
    "Noto Sans Osmanya Regular",
    "Noto Sans Pahawh Hmong Regular",
    "Noto Sans Palmyrene Regular",
    "Noto Sans Pau Cin Hau Regular",
    "Noto Sans PhagsPa Regular",
    "Noto Sans Phoenician Regular",
    "Noto Sans Psalter Pahlavi Regular",
    "Noto Sans Rejang Regular",
    "Noto Sans Samaritan Regular",
    "Noto Sans Saurashtra Regular",
    "Noto Sans Sharada Regular",
    "Noto Sans Siddham Regular",
    "Noto Sans Sora Sompeng Regular",
    "Noto Sans Sundanese Regular",
    "Noto Sans Syloti Nagri Regular",
    "Noto Sans Syriac Regular Black",
    "Noto Sans Syriac Regular Bold",
    "Noto Sans Syriac Regular ExtraBold",
    "Noto Sans Syriac Regular ExtraLight",
    "Noto Sans Syriac Regular Light",
    "Noto Sans Syriac Regular Medium",
    "Noto Sans Syriac Regular Regular",
    "Noto Sans Syriac Regular SemiBold",
    "Noto Sans Syriac Regular Thin",
    "Noto Sans Tagalog Regular",
    "Noto Sans Tagbanwa Regular",
    "Noto Sans Tai Le Regular",
    "Noto Sans Tai Tham",
    "Noto Sans Tai Viet Regular",
    "Noto Sans Takri Regular",
    "Noto Sans Thaana Regular",
    "Noto Sans Tifinagh Regular",
    "Noto Sans Tirhuta Regular",
    "Noto Sans Ugaritic Regular",
    "Noto Sans Vai Regular",
    "Noto Sans Wancho Regular",
    "Noto Sans Warang Citi Regular",
    "Noto Sans Yi Regular",
    "Noto Sans Zawgyi Black",
    "Noto Sans Zawgyi Bold",
    "Noto Sans Zawgyi ExtraBold",
    "Noto Sans Zawgyi ExtraLight",
    "Noto Sans Zawgyi Light",
    "Noto Sans Zawgyi Medium",
    "Noto Sans Zawgyi Regular",
    "Noto Sans Zawgyi SemiBold",
    "Noto Sans Zawgyi Thin",
    "Noto Serif Ahom Regular",
    "Noto Serif Balinese Regular",
    "Noto Serif Hmong Nyiakeng Regular",
    "Noto Serif Kannada Black",
    "Noto Serif Kannada Bold",
    "Noto Serif Kannada ExtraBold",
    "Noto Serif Kannada ExtraLight",
    "Noto Serif Kannada Light",
    "Noto Serif Kannada Medium",
    "Noto Serif Kannada Regular",
    "Noto Serif Kannada SemiBold",
    "Noto Serif Kannada Thin",
    "Noto Serif Myanmar Black",
    "Noto Serif Myanmar Bold",
    "Noto Serif Myanmar ExtraBold",
    "Noto Serif Myanmar ExtraLight",
    "Noto Serif Myanmar Light",
    "Noto Serif Myanmar Medium",
    "Noto Serif Myanmar Regular",
    "Noto Serif Myanmar SemiBold",
    "Noto Serif Myanmar Thin",
    "Noto Serif Yezidi Regular",
    "November Bangla Traditional Regular Black",
    "November Bangla Traditional Regular Bold",
    "November Bangla Traditional Regular Compressed Black",
    "November Bangla Traditional Regular Compressed Bold",
    "November Bangla Traditional Regular Compressed Extralight",
    "November Bangla Traditional Regular Compressed Hairline",
    "November Bangla Traditional Regular Compressed Heavy",
    "November Bangla Traditional Regular Compressed Light",
    "November Bangla Traditional Regular Compressed Medium",
    "November Bangla Traditional Regular Compressed Regular",
    "November Bangla Traditional Regular Compressed Thin",
    "November Bangla Traditional Regular Condensed Black",
    "November Bangla Traditional Regular Condensed Bold",
    "November Bangla Traditional Regular Condensed Extralight",
    "November Bangla Traditional Regular Condensed Hairline",
    "November Bangla Traditional Regular Condensed Heavy",
    "November Bangla Traditional Regular Condensed Light",
    "November Bangla Traditional Regular Condensed Medium",
    "November Bangla Traditional Regular Condensed Regular",
    "November Bangla Traditional Regular Condensed Thin",
    "November Bangla Traditional Regular Extralight",
    "November Bangla Traditional Regular Hairline",
    "November Bangla Traditional Regular Heavy",
    "November Bangla Traditional Regular Light",
    "November Bangla Traditional Regular Medium",
    "November Bangla Traditional Regular Regular",
    "November Bangla Traditional Regular Thin",
    "October Compressed Devanagari Black",
    "October Compressed Devanagari Bold",
    "October Compressed Devanagari ExtraLight",
    "October Compressed Devanagari Hairline",
    "October Compressed Devanagari Heavy",
    "October Compressed Devanagari Light",
    "October Compressed Devanagari Medium",
    "October Compressed Devanagari Regular",
    "October Compressed Devanagari Thin",
    "October Compressed Gujarati Black",
    "October Compressed Gujarati Bold",
    "October Compressed Gujarati ExtraLight",
    "October Compressed Gujarati Hairline",
    "October Compressed Gujarati Heavy",
    "October Compressed Gujarati Light",
    "October Compressed Gujarati Medium",
    "October Compressed Gujarati Regular",
    "October Compressed Gujarati Thin",
    "October Compressed Gurmukhi Black",
    "October Compressed Gurmukhi Bold",
    "October Compressed Gurmukhi ExtraLight",
    "October Compressed Gurmukhi Hairline",
    "October Compressed Gurmukhi Heavy",
    "October Compressed Gurmukhi Light",
    "October Compressed Gurmukhi Medium",
    "October Compressed Gurmukhi Regular",
    "October Compressed Gurmukhi Thin",
    "October Compressed Kannada Black",
    "October Compressed Kannada Bold",
    "October Compressed Kannada ExtraLight",
    "October Compressed Kannada Hairline",
    "October Compressed Kannada Heavy",
    "October Compressed Kannada Light",
    "October Compressed Kannada Medium",
    "October Compressed Kannada Regular",
    "October Compressed Kannada Thin",
    "October Compressed Meetei Mayek Black",
    "October Compressed Meetei Mayek Bold",
    "October Compressed Meetei Mayek ExtraLight",
    "October Compressed Meetei Mayek Hairline",
    "October Compressed Meetei Mayek Heavy",
    "October Compressed Meetei Mayek Light",
    "October Compressed Meetei Mayek Medium",
    "October Compressed Meetei Mayek Regular",
    "October Compressed Meetei Mayek Thin",
    "October Compressed Odia Black",
    "October Compressed Odia Bold",
    "October Compressed Odia ExtraLight",
    "October Compressed Odia Hairline",
    "October Compressed Odia Heavy",
    "October Compressed Odia Light",
    "October Compressed Odia Medium",
    "October Compressed Odia Regular",
    "October Compressed Odia Thin",
    "October Compressed Ol Chiki Black",
    "October Compressed Ol Chiki Bold",
    "October Compressed Ol Chiki ExtraLight",
    "October Compressed Ol Chiki Hairline",
    "October Compressed Ol Chiki Heavy",
    "October Compressed Ol Chiki Light",
    "October Compressed Ol Chiki Medium",
    "October Compressed Ol Chiki Regular",
    "October Compressed Ol Chiki Thin",
    "October Compressed Tamil Black",
    "October Compressed Tamil Bold",
    "October Compressed Tamil ExtraLight",
    "October Compressed Tamil Hairline",
    "October Compressed Tamil Heavy",
    "October Compressed Tamil Light",
    "October Compressed Tamil Medium",
    "October Compressed Tamil Regular",
    "October Compressed Tamil Thin",
    "October Compressed Telugu Black",
    "October Compressed Telugu Bold",
    "October Compressed Telugu ExtraLight",
    "October Compressed Telugu Hairline",
    "October Compressed Telugu Heavy",
    "October Compressed Telugu Light",
    "October Compressed Telugu Medium",
    "October Compressed Telugu Regular",
    "October Compressed Telugu Thin",
    "October Condensed Devanagari Black",
    "October Condensed Devanagari Bold",
    "October Condensed Devanagari ExtraLight",
    "October Condensed Devanagari Hairline",
    "October Condensed Devanagari Heavy",
    "October Condensed Devanagari Light",
    "October Condensed Devanagari Medium",
    "October Condensed Devanagari Regular",
    "October Condensed Devanagari Thin",
    "October Condensed Gujarati Black",
    "October Condensed Gujarati Bold",
    "October Condensed Gujarati ExtraLight",
    "October Condensed Gujarati Hairline",
    "October Condensed Gujarati Heavy",
    "October Condensed Gujarati Light",
    "October Condensed Gujarati Medium",
    "October Condensed Gujarati Regular",
    "October Condensed Gujarati Thin",
    "October Condensed Gurmukhi Black",
    "October Condensed Gurmukhi Bold",
    "October Condensed Gurmukhi ExtraLight",
    "October Condensed Gurmukhi Hairline",
    "October Condensed Gurmukhi Heavy",
    "October Condensed Gurmukhi Light",
    "October Condensed Gurmukhi Medium",
    "October Condensed Gurmukhi Regular",
    "October Condensed Gurmukhi Thin",
    "October Condensed Kannada Black",
    "October Condensed Kannada Bold",
    "October Condensed Kannada ExtraLight",
    "October Condensed Kannada Hairline",
    "October Condensed Kannada Heavy",
    "October Condensed Kannada Light",
    "October Condensed Kannada Medium",
    "October Condensed Kannada Regular",
    "October Condensed Kannada Thin",
    "October Condensed Meetei Mayek Black",
    "October Condensed Meetei Mayek Bold",
    "October Condensed Meetei Mayek ExtraLight",
    "October Condensed Meetei Mayek Hairline",
    "October Condensed Meetei Mayek Heavy",
    "October Condensed Meetei Mayek Light",
    "October Condensed Meetei Mayek Medium",
    "October Condensed Meetei Mayek Regular",
    "October Condensed Meetei Mayek Thin",
    "October Condensed Odia Black",
    "October Condensed Odia Bold",
    "October Condensed Odia ExtraLight",
    "October Condensed Odia Hairline",
    "October Condensed Odia Heavy",
    "October Condensed Odia Light",
    "October Condensed Odia Medium",
    "October Condensed Odia Regular",
    "October Condensed Odia Thin",
    "October Condensed Ol Chiki Black",
    "October Condensed Ol Chiki Bold",
    "October Condensed Ol Chiki ExtraLight",
    "October Condensed Ol Chiki Hairline",
    "October Condensed Ol Chiki Heavy",
    "October Condensed Ol Chiki Light",
    "October Condensed Ol Chiki Medium",
    "October Condensed Ol Chiki Regular",
    "October Condensed Ol Chiki Thin",
    "October Condensed Tamil Black",
    "October Condensed Tamil Bold",
    "October Condensed Tamil ExtraLight",
    "October Condensed Tamil Hairline",
    "October Condensed Tamil Heavy",
    "October Condensed Tamil Light",
    "October Condensed Tamil Medium",
    "October Condensed Tamil Regular",
    "October Condensed Tamil Thin",
    "October Condensed Telugu Black",
    "October Condensed Telugu Bold",
    "October Condensed Telugu ExtraLight",
    "October Condensed Telugu Hairline",
    "October Condensed Telugu Heavy",
    "October Condensed Telugu Light",
    "October Condensed Telugu Medium",
    "October Condensed Telugu Regular",
    "October Condensed Telugu Thin",
    "October Devanagari Black",
    "October Devanagari Bold",
    "October Devanagari ExtraLight",
    "October Devanagari Hairline",
    "October Devanagari Heavy",
    "October Devanagari Light",
    "October Devanagari Medium",
    "October Devanagari Regular",
    "October Devanagari Thin",
    "October Gujarati Black",
    "October Gujarati Bold",
    "October Gujarati ExtraLight",
    "October Gujarati Hairline",
    "October Gujarati Heavy",
    "October Gujarati Light",
    "October Gujarati Medium",
    "October Gujarati Regular",
    "October Gujarati Thin",
    "October Gurmukhi Black",
    "October Gurmukhi Bold",
    "October Gurmukhi ExtraLight",
    "October Gurmukhi Hairline",
    "October Gurmukhi Heavy",
    "October Gurmukhi Light",
    "October Gurmukhi Medium",
    "October Gurmukhi Regular",
    "October Gurmukhi Thin",
    "October Kannada Black",
    "October Kannada Bold",
    "October Kannada ExtraLight",
    "October Kannada Hairline",
    "October Kannada Heavy",
    "October Kannada Light",
    "October Kannada Medium",
    "October Kannada Regular",
    "October Kannada Thin",
    "October Meetei Mayek Black",
    "October Meetei Mayek Bold",
    "October Meetei Mayek ExtraLight",
    "October Meetei Mayek Hairline",
    "October Meetei Mayek Heavy",
    "October Meetei Mayek Light",
    "October Meetei Mayek Medium",
    "October Meetei Mayek Regular",
    "October Meetei Mayek Thin",
    "October Odia Black",
    "October Odia Bold",
    "October Odia ExtraLight",
    "October Odia Hairline",
    "October Odia Heavy",
    "October Odia Light",
    "October Odia Medium",
    "October Odia Regular",
    "October Odia Thin",
    "October Ol Chiki Black",
    "October Ol Chiki Bold",
    "October Ol Chiki ExtraLight",
    "October Ol Chiki Hairline",
    "October Ol Chiki Heavy",
    "October Ol Chiki Light",
    "October Ol Chiki Medium",
    "October Ol Chiki Regular",
    "October Ol Chiki Thin",
    "October Tamil Black",
    "October Tamil Bold",
    "October Tamil ExtraLight",
    "October Tamil Hairline",
    "October Tamil Heavy",
    "October Tamil Light",
    "October Tamil Medium",
    "October Tamil Regular",
    "October Tamil Thin",
    "October Telugu Black",
    "October Telugu Bold",
    "October Telugu ExtraLight",
    "October Telugu Hairline",
    "October Telugu Heavy",
    "October Telugu Light",
    "October Telugu Medium",
    "October Telugu Regular",
    "October Telugu Thin",
    "Optima Bold",
    "Optima Bold Italic",
    "Optima ExtraBlack",
    "Optima Italic",
    "Optima Regular",
    "Oriya MN",
    "Oriya MN Bold",
    "Oriya Sangam MN",
    "Oriya Sangam MN Bold",
    "Osaka",
    "Osaka-Mono",
    "PCMyungjo Regular",
    "PSL Ornanong Pro",
    "PSL Ornanong Pro Bold",
    "PSL Ornanong Pro Bold Italic",
    "PSL Ornanong Pro Demibold",
    "PSL Ornanong Pro Demibold Italic",
    "PSL Ornanong Pro Italic",
    "PSL Ornanong Pro Light",
    "PSL Ornanong Pro Light Italic",
    "PT Mono",
    "PT Mono Bold",
    "PT Sans",
    "PT Sans Bold",
    "PT Sans Bold Italic",
    "PT Sans Caption",
    "PT Sans Caption Bold",
    "PT Sans Italic",
    "PT Sans Narrow",
    "PT Sans Narrow Bold",
    "PT Serif",
    "PT Serif Bold",
    "PT Serif Bold Italic",
    "PT Serif Caption",
    "PT Serif Caption Italic",
    "PT Serif Italic",
    "Padyakke Expanded One",
    "Palatino",
    "Palatino Bold",
    "Palatino Bold Italic",
    "Palatino Italic",
    "Papyrus",
    "Papyrus Condensed",
    "Party LET Plain",
    "Phosphate Inline",
    "Phosphate Solid",
    "PilGi Regular",
    "PingFang HK Light",
    "PingFang HK Medium",
    "PingFang HK Regular",
    "PingFang HK Semibold",
    "PingFang HK Thin",
    "PingFang HK Ultralight",
    "PingFang MO Light",
    "PingFang MO Medium",
    "PingFang MO Regular",
    "PingFang MO Semibold",
    "PingFang MO Thin",
    "PingFang MO Ultralight",
    "PingFang SC Light",
    "PingFang SC Medium",
    "PingFang SC Regular",
    "PingFang SC Semibold",
    "PingFang SC Thin",
    "PingFang SC Ultralight",
    "PingFang TC Light",
    "PingFang TC Medium",
    "PingFang TC Regular",
    "PingFang TC Semibold",
    "PingFang TC Thin",
    "PingFang TC Ultralight",
    "Plantagenet Cherokee",
    "PortagoITC TT",
    "Princetown LET",
    "Produkt Extralight",
    "Produkt Extralight Italic",
    "Produkt Light",
    "Produkt Light Italic",
    "Produkt Medium",
    "Produkt Medium Italic",
    "Produkt Regular",
    "Produkt Regular Italic",
    "Proxima Nova",
    "Proxima Nova Bold",
    "Proxima Nova Bold It",
    "Proxima Nova Extrabold",
    "Proxima Nova Extrabold It",
    "Proxima Nova It",
    "Proxima Nova Light",
    "Proxima Nova Light It",
    "Proxima Nova Medium",
    "Proxima Nova Medium It",
    "Proxima Nova Semibold",
    "Proxima Nova Semibold It",
    "Publico Headline Black",
    "Publico Headline Black Italic",
    "Publico Headline Bold",
    "Publico Headline Bold Italic",
    "Publico Headline Italic",
    "Publico Headline Roman",
    "Publico Text Bold",
    "Publico Text Bold Italic",
    "Publico Text Italic",
    "Publico Text Roman",
    "Publico Text Semibold",
    "Publico Text Semibold Italic",
    "Quotes Caps Regular",
    "Quotes Script Regular",
    "Raanana",
    "Raanana Bold",
    "Raya Regular",
    "Rockwell",
    "Rockwell Bold",
    "Rockwell Bold Italic",
    "Rockwell Italic",
    "STFangsong",
    "STHeiti",
    "STIX Two Math",
    "STIX Two Math Regular",
    "STIX Two Text Bold",
    "STIX Two Text Bold Italic",
    "STIX Two Text Italic Bold Italic",
    "STIX Two Text Italic Italic",
    "STIX Two Text Italic Medium Italic",
    "STIX Two Text Italic SemiBold Italic",
    "STIX Two Text Medium",
    "STIX Two Text Regular",
    "STIX Two Text SemiBold",
    "STIXGeneral-Bold",
    "STIXGeneral-BoldItalic",
    "STIXGeneral-Italic",
    "STIXGeneral-Regular",
    "STIXIntegralsD-Bold",
    "STIXIntegralsD-Regular",
    "STIXIntegralsSm-Bold",
    "STIXIntegralsSm-Regular",
    "STIXIntegralsUp-Bold",
    "STIXIntegralsUp-Regular",
    "STIXIntegralsUpD-Bold",
    "STIXIntegralsUpD-Regular",
    "STIXIntegralsUpSm-Bold",
    "STIXIntegralsUpSm-Regular",
    "STIXNonUnicode-Bold",
    "STIXNonUnicode-BoldItalic",
    "STIXNonUnicode-Italic",
    "STIXNonUnicode-Regular",
    "STIXSizeFiveSym-Regular",
    "STIXSizeFourSym-Bold",
    "STIXSizeFourSym-Regular",
    "STIXSizeOneSym-Bold",
    "STIXSizeOneSym-Regular",
    "STIXSizeThreeSym-Bold",
    "STIXSizeThreeSym-Regular",
    "STIXSizeTwoSym-Bold",
    "STIXSizeTwoSym-Regular",
    "STIXVariants-Bold",
    "STIXVariants-Regular",
    "STKaiti",
    "STSong",
    "STXihei",
    "Sama Devanagari Bold",
    "Sama Devanagari Book",
    "Sama Devanagari ExtraBold",
    "Sama Devanagari Medium",
    "Sama Devanagari Regular",
    "Sama Devanagari SemiBold",
    "Sama Gujarati Bold",
    "Sama Gujarati Book",
    "Sama Gujarati ExtraBold",
    "Sama Gujarati Medium",
    "Sama Gujarati Regular",
    "Sama Gujarati SemiBold",
    "Sama Gurmukhi Bold",
    "Sama Gurmukhi Book",
    "Sama Gurmukhi ExtraBold",
    "Sama Gurmukhi Medium",
    "Sama Gurmukhi Regular",
    "Sama Gurmukhi SemiBold",
    "Sama Kannada Bold",
    "Sama Kannada Book",
    "Sama Kannada ExtraBold",
    "Sama Kannada Medium",
    "Sama Kannada Regular",
    "Sama Kannada SemiBold",
    "Sama Malayalam Bold",
    "Sama Malayalam Book",
    "Sama Malayalam ExtraBold",
    "Sama Malayalam Medium",
    "Sama Malayalam Regular",
    "Sama Malayalam SemiBold",
    "Sama Tamil Bold",
    "Sama Tamil Book",
    "Sama Tamil ExtraBold",
    "Sama Tamil Medium",
    "Sama Tamil Regular",
    "Sama Tamil SemiBold",
    "Sana Regular",
    "Santa Fe LET Plain:1.0",
    "Sarabun Bold",
    "Sarabun Bold Italic",
    "Sarabun ExtraBold",
    "Sarabun ExtraBold Italic",
    "Sarabun ExtraLight",
    "Sarabun ExtraLight Italic",
    "Sarabun Italic",
    "Sarabun Light",
    "Sarabun Light Italic",
    "Sarabun Medium",
    "Sarabun Medium Italic",
    "Sarabun Regular",
    "Sarabun SemiBold",
    "Sarabun SemiBold Italic",
    "Sarabun Thin",
    "Sarabun Thin Italic",
    "Sathu",
    "Sauber Script",
    "Savoye LET Plain:1.0",
    "Scheme-Bold",
    "SchoolHouse Cursive B",
    "SchoolHouse Printed A",
    "Seravek",
    "Seravek Bold",
    "Seravek Bold Italic",
    "Seravek ExtraLight",
    "Seravek ExtraLight Italic",
    "Seravek Italic",
    "Seravek Light",
    "Seravek Light Italic",
    "Seravek Medium",
    "Seravek Medium Italic",
    "Shobhika Bold",
    "Shobhika Regular",
    "Shree Devanagari 714",
    "Shree Devanagari 714 Bold",
    "Shree Devanagari 714 Bold Italic",
    "Shree Devanagari 714 Italic",
    "SignPainter-HouseScript",
    "SignPainter-HouseScript Semibold",
    "Silom",
    "SimSong Bold",
    "SimSong Regular",
    "Sinhala MN",
    "Sinhala MN Bold",
    "Sinhala Sangam MN",
    "Sinhala Sangam MN Bold",
    "Skia Black",
    "Skia Black Condensed",
    "Skia Black Extended",
    "Skia Bold",
    "Skia Condensed",
    "Skia Extended",
    "Skia Light",
    "Skia Light Condensed",
    "Skia Light Extended",
    "Skia Regular",
    "Snell Roundhand",
    "Snell Roundhand Black",
    "Snell Roundhand Bold",
    "Somer Regular",
    "Songti SC Black",
    "Songti SC Bold",
    "Songti SC Light",
    "Songti SC Regular",
    "Songti TC Bold",
    "Songti TC Light",
    "Songti TC Regular",
    "Spot Mono Bold",
    "Spot Mono Medium",
    "Spot Mono Regular",
    "Srisakdi Bold",
    "Srisakdi Regular",
    "Stone Sans ITC TT Bold",
    "Stone Sans Sem ITC TT Semi",
    "Stone Sans Sem ITC TT SemiIta",
    "Sukhumvit Set Bold",
    "Sukhumvit Set Light",
    "Sukhumvit Set Medium",
    "Sukhumvit Set Semi Bold",
    "Sukhumvit Set Text",
    "Sukhumvit Set Thin",
    "Superclarendon Black",
    "Superclarendon Black Italic",
    "Superclarendon Bold",
    "Superclarendon Bold Italic",
    "Superclarendon Italic",
    "Superclarendon Light",
    "Superclarendon Light Italic",
    "Superclarendon Regular",
    "Symbol",
    "Synchro LET",
    "Tahoma",
    "Tahoma Bold",
    "Tamil MN",
    "Tamil MN Bold",
    "Tamil Sangam MN",
    "Tamil Sangam MN Black",
    "Tamil Sangam MN Bold",
    "Tamil Sangam MN Demibold",
    "Tamil Sangam MN Light",
    "Tamil Sangam MN Medium",
    "Telugu MN",
    "Telugu MN Bold",
    "Telugu Sangam MN",
    "Telugu Sangam MN Bold",
    "The Hand Serif Semibold",
    "Thonburi",
    "Thonburi Bold",
    "Thonburi Light",
    "Times Bold",
    "Times Bold Italic",
    "Times Italic",
    "Times New Roman",
    "Times New Roman Bold",
    "Times New Roman Bold Italic",
    "Times New Roman Italic",
    "Times Roman",
    "Tiro Bangla",
    "Tiro Bangla Italic",
    "Tiro Devanagari Hindi",
    "Tiro Devanagari Hindi Italic",
    "Tiro Devanagari Marathi",
    "Tiro Devanagari Marathi Italic",
    "Tiro Devanagari Sanskrit",
    "Tiro Devanagari Sanskrit Italic",
    "Tiro Gurmukhi",
    "Tiro Gurmukhi Italic",
    "Tiro Kannada",
    "Tiro Kannada Italic",
    "Tiro Tamil",
    "Tiro Tamil Italic",
    "Tiro Telugu",
    "Tiro Telugu Italic",
    "Toppan Bunkyu Gothic Demibold",
    "Toppan Bunkyu Gothic Regular",
    "Toppan Bunkyu Midashi Gothic Extrabold",
    "Toppan Bunkyu Midashi Mincho Extrabold",
    "Toppan Bunkyu Mincho Regular",
    "Trattatello",
    "Trebuchet MS",
    "Trebuchet MS Bold",
    "Trebuchet MS Bold Italic",
    "Trebuchet MS Italic",
    "Tsukushi A Round Gothic Bold",
    "Tsukushi A Round Gothic Regular",
    "Tsukushi B Round Gothic Bold",
    "Tsukushi B Round Gothic Regular",
    "Tw Cen MT",
    "Tw Cen MT Bold",
    "Tw Cen MT Bold Italic",
    "Tw Cen MT Italic",
    "Type Embellishments One LET Embellishments One LET Plain:1.0",
    "Verdana",
    "Verdana Bold",
    "Verdana Bold Italic",
    "Verdana Italic",
    "Waseem Light",
    "Waseem Regular",
    "Wawati SC Regular",
    "Wawati TC Regular",
    "Webdings",
    "Weibei SC Bold",
    "Weibei TC Bold",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3",
    "Xingkai SC Bold",
    "Xingkai SC Light",
    "Xingkai TC Bold",
    "Xingkai TC Light",
    "Yaziji Regular",
    "YuGothic Bold",
    "YuGothic Medium",
    "YuKyokasho Bold",
    "YuKyokasho Medium",
    "YuKyokasho Yoko Bold",
    "YuKyokasho Yoko Medium",
    "YuMincho +36p Kana Demibold",
    "YuMincho +36p Kana Extrabold",
    "YuMincho +36p Kana Medium",
    "YuMincho Demibold",
    "YuMincho Extrabold",
    "YuMincho Medium",
    "Yuanti SC Bold",
    "Yuanti SC Light",
    "Yuanti SC Regular",
    "Yuanti TC Bold",
    "Yuanti TC Light",
    "Yuanti TC Regular",
    "Yuppy SC Regular",
    "Yuppy TC Regular",
    "Zapf Dingbats",
    "Zapfino",
    "Zawra Bold",
    "Zawra Heavy"
];

const IPA_FONT_FAMILY_LIST = [
    'IPAmjMincho',
    'IPAPMincho',
    'IPAPGothic',
    'IPAMincho',
    'IPAGothic',
];

const NOTO_CJK_FONT_FAMILY_LIST = [
    'Noto Sans Japanese',
    'Noto Sans Traditional Chinese',
    'Noto Sans Simplified Chinese',
    'Noto Sans Hong Kong',
    'Noto Sans Korean'
];

const knownFonts = [
    'NotExistsFontName',
    ...WINDOWS_FONT_FAMILY_LIST,
    ...MS_OFFICE_FONT_FAMILY_LIST,
    ...APPLE_FONT_FAMILY_LIST,
    ...NOTO_CJK_FONT_FAMILY_LIST,
    ...IPA_FONT_FAMILY_LIST
];

/*
const knownFonts = [
    'NotExistsFontName', // This is a fake font name
    'Agency FB',
    'Algerian',
    'Arial',
    'Arial Rounded MT Bold',
    'Bahnschrift',
    'Baskerville Old Face',
    'Bauhaus 93',
    'Bell MT',
    'Berlin Sans FB',
    'Berlin Sans FB Demi',
    'Blackadder ITC',
    'Bodoni MT',
    'Bodoni MT Poster Compressed',
    'Book Antiqua',
    'Bookman Old Style',
    'Bookshelf Symbol 7',
    'Bradley Hand ITC',
    'Britannic Bold',
    'Broadway',
    'Brush Script MT',
    'Calibri',
    'Californian FB',
    'Calisto MT',
    'Cambria',
    'Cambria Math',
    'Candara',
    'Cascadia Code',
    'Cascadea Mono',
    'Castellar',
    'Centaur',
    'Century Gothic',
    'Century Schoolbook',
    'Century',
    'Chiller',
    'Colonna MT',
    'Comic Sans MS',
    'Consolas',
    'Constantia',
    'Cooper Black',
    'Copperplate Gothic Bold',
    'Copperplate Gothic Light',
    'Corbel',
    'Courier New',
    'Courier',
    'Curlz MT',
    'Dubai',
    'Ebrima',
    'Edwardian Script ITC',
    'Elephant',
    'Engravers MT',
    'Eras ITC',
    'Felix Titling',
    'Fixedsys',
    'Footlight MT Light',
    'Forte',
    'Franklin Gothic',
    'Franklin Gothic Book',
    'Freestyle Script',
    'French Script MT',
    'Gabriola',
    'Gadugi',
    'Garamond',
    'Georgia',
    'Gigi',
    'Gill Sans',
    'Gill Sans MT',
    'Gloucester MT Extra Condensed',
    'Goudy Old Style',
    'Goudy Stout',
    'Haettenschweiler',
    'Harlow Solid Italic',
    'Harrington',
    'Noto Sans',
    'Noto Sans Japanese',
    'Noto Sans Traditional Chinese',
    'Noto Sans Simplified Chinese',
    'Noto Sans Hong Kong',
    'Noto Sans Korean',
    'BIZ UDPGothic',
    'BIZ UDPMincho',
    'BIZ UDGothic',
    'BIZ UDMincho',
    'HGPGothicE',
    'Hiragino Kaku Gothic Pro',
    'Hiragino Kaku Gothic ProN',
    'Hiragino Kaku Gothic Std',
    'Hiragino Kaku Gothic StdN',
    'Hiragino Maru Gothic Pro',
    'Hiragino Maru Gothic ProN',
    'Hiragino Mincho Pro',
    'Hiragino Mincho ProN',
    'Hiragino Sans',
    'Hiragino Sans CNS',
    'Hiragino Sans GB',
    'Hiragino Sans TC',
    'Osaka',
    'MS Gothic',
    'MS PGothic',
    'MS UI Gothic',
    'MS Mincho',
    'MS PMincho',
    'Meiryo',
    'Meiryo UI',
    'Yu Gothic',
    'Yu Mincho',
    'Segoe UI',
    'IPAmjMincho',
    'IPAPMincho',
    'IPAPGothic',
    'IPAMincho',
    'IPAGothic',
    'Noto Nastaliq Urdu',
    'Noto Nastaliq Urdu Bold',
    'Noto Sans Adlam Regular',
    'Noto Sans Armenian Black',
    'Noto Sans Armenian Bold',
    'Noto Sans Armenian ExtraBold',
    'Noto Sans Armenian ExtraLight',
    'Noto Sans Armenian Light',
    'Noto Sans Armenian Medium',
    'Noto Sans Armenian Regular',
    'Noto Sans Armenian SemiBold',
    'Noto Sans Armenian Thin',
    'Noto Sans Avestan Regular',
    'Noto Sans Bamum Regular',
    'Noto Sans Bassa Vah Regular',
    'Noto Sans Batak Regular',
    'Noto Sans Bhaiksuki Regular',
    'Noto Sans Brahmi Regular',
    'Noto Sans Buginese Regular',
    'Noto Sans Buhid Regular',
    'Noto Sans Canadian Aboriginal Regular',
    'Noto Sans Carian Regular',
    'Noto Sans Caucasian Albanian Regular',
    'Noto Sans Chakma Regular',
    'Noto Sans Cham Regular',
    'Noto Sans Coptic Regular',
    'Noto Sans Cuneiform Regular',
    'Noto Sans Cypriot Regular',
    'Noto Sans Duployan Regular',
    'Noto Sans Egyptian Hieroglyphs Regular',
    'Noto Sans Elbasan Regular',
    'Noto Sans Glagolitic Regular',
    'Noto Sans Gothic Regular',
    'Noto Sans Gunjala Gondi Regular',
    'Noto Sans Hanifi Rohingya Regular',
    'Noto Sans Hanunoo Regular',
    'Noto Sans Hatran Regular',
    'Noto Sans Imperial Aramaic Regular',
    'Noto Sans Inscriptional Pahlavi Regular',
    'Noto Sans Inscriptional Parthian Regular',
    'Noto Sans Javanese Regular',
    'Noto Sans Kaithi Regular',
    'Noto Sans Kannada Black',
    'Noto Sans Kannada Bold',
    'Noto Sans Kannada ExtraBold',
    'Noto Sans Kannada ExtraLight',
    'Noto Sans Kannada Light',
    'Noto Sans Kannada Medium',
    'Noto Sans Kannada Regular',
    'Noto Sans Kannada SemiBold',
    'Noto Sans Kannada Thin',
    'Noto Sans Kayah Li Regular',
    'Noto Sans Kharoshthi Regular',
    'Noto Sans Khojki Regular',
    'Noto Sans Khudawadi Regular',
    'Noto Sans Lepcha Regular',
    'Noto Sans Limbu Regular',
    'Noto Sans Linear A Regular',
    'Noto Sans Linear B Regular',
    'Noto Sans Lisu Regular',
    'Noto Sans Lycian Regular',
    'Noto Sans Lydian Regular',
    'Noto Sans Mahajani Regular',
    'Noto Sans Mandaic Regular',
    'Noto Sans Manichaean Regular',
    'Noto Sans Marchen Regular',
    'Noto Sans Masaram Gondi Regular',
    'Noto Sans Meetei Mayek Regular',
    'Noto Sans Mende Kikakui Regular',
    'Noto Sans Meroitic Regular',
    'Noto Sans Miao Regular',
    'Noto Sans Modi Regular',
    'Noto Sans Mongolian',
    'Noto Sans Mro Regular',
    'Noto Sans Multani Regular',
    'Noto Sans Myanmar Black',
    'Noto Sans Myanmar Bold',
    'Noto Sans Myanmar ExtraBold',
    'Noto Sans Myanmar ExtraLight',
    'Noto Sans Myanmar Light',
    'Noto Sans Myanmar Medium',
    'Noto Sans Myanmar Regular',
    'Noto Sans Myanmar SemiBold',
    'Noto Sans Myanmar Thin',
    'Noto Sans NKo Regular',
    'Noto Sans Nabataean Regular',
    'Noto Sans New Tai Lue Regular',
    'Noto Sans Newa Regular',
    'Noto Sans Ol Chiki Regular',
    'Noto Sans Old Hungarian Regular',
    'Noto Sans Old Italic Regular',
    'Noto Sans Old North Arabian Regular',
    'Noto Sans Old Permic Regular',
    'Noto Sans Old Persian Regular',
    'Noto Sans Old South Arabian Regular',
    'Noto Sans Old Turkic Regular',
    'Noto Sans Oriya',
    'Noto Sans Oriya Bold',
    'Noto Sans Osage Regular',
    'Noto Sans Osmanya Regular',
    'Noto Sans Pahawh Hmong Regular',
    'Noto Sans Palmyrene Regular',
    'Noto Sans Pau Cin Hau Regular',
    'Noto Sans PhagsPa Regular',
    'Noto Sans Phoenician Regular',
    'Noto Sans Psalter Pahlavi Regular',
    'Noto Sans Rejang Regular',
    'Noto Sans Samaritan Regular',
    'Noto Sans Saurashtra Regular',
    'Noto Sans Sharada Regular',
    'Noto Sans Siddham Regular',
    'Noto Sans Sora Sompeng Regular',
    'Noto Sans Sundanese Regular',
    'Noto Sans Syloti Nagri Regular',
    'Noto Sans Syriac Regular Black',
    'Noto Sans Syriac Regular Bold',
    'Noto Sans Syriac Regular ExtraBold',
    'Noto Sans Syriac Regular ExtraLight',
    'Noto Sans Syriac Regular Light',
    'Noto Sans Syriac Regular Medium',
    'Noto Sans Syriac Regular Regular',
    'Noto Sans Syriac Regular SemiBold',
    'Noto Sans Syriac Regular Thin',
    'Noto Sans Tagalog Regular',
    'Noto Sans Tagbanwa Regular',
    'Noto Sans Tai Le Regular',
    'Noto Sans Tai Tham',
    'Noto Sans Tai Viet Regular',
    'Noto Sans Takri Regular',
    'Noto Sans Thaana Regular',
    'Noto Sans Tifinagh Regular',
    'Noto Sans Tirhuta Regular',
    'Noto Sans Ugaritic Regular',
    'Noto Sans Vai Regular',
    'Noto Sans Wancho Regular',
    'Noto Sans Warang Citi Regular',
    'Noto Sans Yi Regular',
    'Noto Sans Zawgyi Black',
    'Noto Sans Zawgyi Bold',
    'Noto Sans Zawgyi ExtraBold',
    'Noto Sans Zawgyi ExtraLight',
    'Noto Sans Zawgyi Light',
    'Noto Sans Zawgyi Medium',
    'Noto Sans Zawgyi Regular',
    'Noto Sans Zawgyi SemiBold',
    'Noto Sans Zawgyi Thin',
    'Noto Serif Ahom Regular',
    'Noto Serif Balinese Regular',
    'Noto Serif Hmong Nyiakeng Regular',
    'Noto Serif Kannada Black',
    'Noto Serif Kannada Bold',
    'Noto Serif Kannada ExtraBold',
    'Noto Serif Kannada ExtraLight',
    'Noto Serif Kannada Light',
    'Noto Serif Kannada Medium',
    'Noto Serif Kannada Regular',
    'Noto Serif Kannada SemiBold',
    'Noto Serif Kannada Thin',
    'Noto Serif Myanmar Black',
    'Noto Serif Myanmar Bold',
    'Noto Serif Myanmar ExtraBold',
    'Noto Serif Myanmar ExtraLight',
    'Noto Serif Myanmar Light',
    'Noto Serif Myanmar Medium',
    'Noto Serif Myanmar Regular',
    'Noto Serif Myanmar SemiBold',
    'Noto Serif Myanmar Thin',
];
*/

function isFontAvailable(font, text) {
    const canvas = document.createElement('canvas');
    const context = canvas.getContext('2d');
    // const text = 'abcdefghijklmnopqrstuvwxyz0123456789';
    context.font = `40px '${font}', 'Adobe Blank'`;
    const newWidth = context.measureText(text).width;
    console.log(`${font}:${newWidth}`);
    return newWidth > 0;
}

function isFontSupportText(font, text) {
    const canvas = document.createElement('canvas');
    const context = canvas.getContext('2d');
    // const text = 'あ';
    // context.font = `40px '${font}', 'Adobe Blank'`;
    // const newWidth = context.measureText(text).width;
    // if (newWidth == 0) {
    //     return false;
    // }

    canvas.width = 200;
    canvas.height = 200;

    context.font = `100px ''`;
    context.fillText(text, 10, 150);
    const imageDataDefault = context.getImageData(0, 0, 200, 200);

    context.clearRect(0, 0, 200, 200);
    context.font = `100px '${font}'`;
    context.fillText(text, 10, 150);

    const imageDataFont = context.getImageData(0, 0, 200, 200);
    if (imageDataDefault.data.length !== imageDataFont.data.length) {
        return false;
    }
    if (imageDataDefault.data.join('') === imageDataFont.data.join('')) {
        return false;
    }
    return true;
}

function isFontAvailable2(font) {
    const span = document.createElement('span');
    span.style.position = 'absolute';
    span.style.left = '-9999px';
    span.style.top = '-9999px';
    span.style.visibility = 'hidden';
    span.style.fontFamily = `'${font}', 'Adobe Blank'`;
    span.style.fontSize = '40px';
    span.innerHTML = 'abcdefghijklmnopqrstuvwxyz0123456789';
    document.body.appendChild(span);
    return span.clientWidth > 0;
}

function detectFonts() {
    const detectedFonts = [];
    // filter dupicated fonts
    const uniqueKnownFonts = knownFonts.filter((font, i, self) => self.indexOf(font) === i);
    let text = document.getElementById("inputText").value;
    if (text.length === 0) {
        text = "A";
    }
    uniqueKnownFonts.forEach(font => {
        if (isFontAvailable(font, text)) {
            const isExceptDefault = document.getElementById("exceptDefault").checked;
            if (isExceptDefault) {
                if (!isFontSupportText(font, text)) {
                    return;
                }
            }

            detectedFonts.push(font);
        }
    });
    return detectedFonts;
}

function addFontSample(fontFamilyName) {
    const sample = document.createElement('div');
    const fontFamilyId = fontFamilyName.replace(/ /g, '_');
    sample.innerHTML = `<span style="white-space: no-wrap">${fontFamilyName}: </span><span id="${fontFamilyId}" style="font: 32px '${fontFamilyName}'; white-space: nowrap"></span>`;
    // sample.innerHTML = `<span>${fontFamilyName}</span><span style="font: 32px '${fontFamilyName}'; white-space: nowrap"> !&#x22;#$%&#x26;&#x27;()*+,-./0123456789:;&lt;=&gt;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_&#x60;abcdefghijklmnopqrstuvwxyz{|}~あ永</span>`;
    document.getElementById("fontSamples").appendChild(sample);
    document.getElementById(fontFamilyId).innerText = document.getElementById("inputText").value;
    // document.body.appendChild(sample);
}

function addFontSampleAll(detectedFonts) {
    document.getElementById("fontSamples").innerHTML = "";
    detectedFonts.forEach(font => {
        addFontSample(font);
    });
}

function init() {
    document.fonts.load('40px "Adobe Blank"', "abcdefghijklmnopqrstuvwxyz0123456789").then(() => {
        console.log('Adobe Blank loaded');
    });
    document.fonts.ready.then(() => {
        console.log('All fonts loaded');
        const detectedFonts = detectFonts();
        console.log('Detected fonts:', detectedFonts);
        if (detectedFonts.length === 0) {
            console.log('No known fonts detected');
        }
        addFontSampleAll(detectedFonts);
    });
    document.getElementById("detectButton").addEventListener('click', () => {
        const detectedFonts = detectFonts();
        addFontSampleAll(detectedFonts);
    });
}

init();
