services:
  devcontainer:
    build: ./workspace/docker
    tty: true
    volumes:
      - ../:/home/node/workspace
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ../clientwebexp
        target: /usr/share/nginx/html
      # - type: bind
      #   source: ./nginx/conf.d/tls
      #   target: /etc/nginx/conf.d/tls
