services:
  workspace:
    build:
      context: ./workspace/docker
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
    tty: true
  nginx:
    image: nginx:1.21
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - type: bind
        source: ..
        target: /var/www/html
      - type: bind
        source: ./nginx/etc/nginx
        target: /etc/nginx
      - type: bind
        source: ./nginx/var/log
        target: /var/log
