services:
  devcontainer:
    build: ./workspace/docker
    tty: true
    volumes:
      - ../:/home/node/workspace
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/tls:/etc/nginx/conf.d/tls
      - ../clientwebexp:/usr/share/nginx/html
